### ISSUE TITLE
I stage

### ISSUE THREAD

**Issue by rusdevops** [lisa-bella97/Stack#1]
@lisa-bella97 

- [x] 1. Присутствует не оптимальное копирование. [здесь](https://github.com/lisa-bella97/Stack/blob/3a14cbe738e4bcd50676958bf2d844b997ad5222/include/stack.hpp#L46-L56).
- [x] 2. Присутствует подключение избыточного заголовочного файла. [здесь](https://github.com/lisa-bella97/Stack/blob/3a14cbe738e4bcd50676958bf2d844b997ad5222/include/stack.hpp#L4).

**Comment by lisa-bella97** [comment]
Closed this in 429b158 and 9315101
