### ISSUE TITLE
III stage

### ISSUE THREAD

**Issue by rusdevops** [lisa-bella97/Stack#2]
@lisa-bella97 

- [x] 1. Присутствует плохо читабельный код [здесь](https://github.com/lisa-bella97/Stack/blob/2029d987d9e3fc228bc01901dbed3991d20c9ee0/include/allocator.hpp#L40-L42). 
Посмотрите пример работы c `std::swap` [здесь](http://www.cplusplus.com/reference/algorithm/swap/).
- [x] 2. Присутствует возможность утечки памяти.
- [x] 3. Присутствует избыточная инструкция. [здесь](https://github.com/lisa-bella97/Stack/blob/2029d987d9e3fc228bc01901dbed3991d20c9ee0/include/allocator.hpp#L54).
- [x] 4. Замените для метода `top` тип возваращаемого значения с `T*` на `T`.

**Comment by lisa-bella97** [comment]
Closed this in commits above
